package ru.borisenko.gennady.sportmonitor.models;


import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "complex_exercise_complex")
public class ComplexExerciseComplex {
    public final static String EXERCISE_COMPLEX_ID_FIELD_NAME = "exercise_complex_id";
    public final static String COMPLEX_ID_FIELD_NAME = "complex_id";

    /**
     * This id is generated by the database and set on the object when it is passed to the create method. An id is
     * needed in case we need to update or delete this object in the future.
     */
    @DatabaseField(generatedId = true)
    private int id;

    // This is a foreign object which just stores the id from the User object in this table.
    @DatabaseField(foreign = true, columnName = EXERCISE_COMPLEX_ID_FIELD_NAME, foreignAutoRefresh = true)
    private ExerciseComplex exercise_complex;

    // This is a foreign object which just stores the id from the Post object in this table.
    @DatabaseField(foreign = true, columnName = COMPLEX_ID_FIELD_NAME, foreignAutoRefresh = true)
    private Complex complex;

    ComplexExerciseComplex() {
        // for ormlite
    }

    public ComplexExerciseComplex(ExerciseComplex exercise_complex, Complex complex) {
        this.exercise_complex = exercise_complex;
        this.complex = complex;
    }

    public int getId() {
        return id;
    }

    public ExerciseComplex getExercise_complex() {
        return exercise_complex;
    }

    public void setExercise_complex(ExerciseComplex exercise_complex) {
        this.exercise_complex = exercise_complex;
    }

    public Complex getComplex() {
        return complex;
    }

    public void setComplex(Complex complex) {
        this.complex = complex;
    }
}
